spring:

  application:
    name: kafkademo

  datasource:
    url: jdbc:postgresql://localhost:5432/kafkademodb
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

kafka:
  address: ${KAFKA_HOST:192.168.1.7}:${KAFKA_PORT:9092}

  topic:
    photo-upload: photo-upload
    photo-upload-dlt: photo-upload.DLT

  consumer:
    group-id: photo-service-group
    dlt-group-id: photo-dlt-consumer
    enable-auto-commit: false
    auto-offset-reset: earliest
    properties:
      max.poll.records: 5
    concurrency: 1

  listener:
    ack-mode: manual