spring:

  application:
    name: kafkademo

  datasource:
    url: jdbc:postgresql://localhost:5432/kafkademodb
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

kafka:
  group-id: photo-service-group
  topic:
    photoUpload: photo-upload
  address: ${KAFKA_HOST:192.168.1.2}:${KAFKA_PORT:9092}

